name: IPlayHub
description: Simple Hub plugin
author: Aubli
version: 0.0.10.1
load: POSTWORLD

main: me.Aubli.IPlayHub.IPlayHub

commands:
    iplayhub:
        description: IPlayHub command
        usage: /<command> ?
        aliases: [iph]